source:
  type: camera
  params:
    index: 0
    width: 1280 # resize before pipeline — all nodes see 1280x720
    height: 720

scene:
  zones:
    - name: AreaA
      polygon:
        - [0.7,0.3] # zone top left
        - [1.0,0.3] # zone top right
        - [1.0,1.0] # zone buttom right
        - [0.7,1.0] # zone buttom left

      color: [255,0,0]

pipeline:
  nodes:
    - name: detectorA
      type: detector
      processor: yolo
      params:
        weights: yolov8n.pt
    - name: trackerA
      type: tracker
      processor: deepsort
      params:
        max_age: 4
        n_init: 3
        nms_max_overlap: 0.5
        max_cosine_distance: 0.3
        nn_budget: 100
    - name: spatial_analyzer
      type: spatial_index
    - name: people_counter
      type: analyzer
      processor: counter
      zone_name: Entrance
      params:
        target_classes:
          - person
        metrics:
          - current
          - cumulative
    - name: count_condition
      type: condition
      params:
        path: analytics.people_counter.person.current
        operator: gt
        value: 10
        true_output: publisherA
    - name: publisherA
      type: publisher
      events:
        - type: count_exceeded_event
          extract:
            count:     analytics.counter.count
            zone_name: analytics.counter.zone_name

  edges:
    - from: detectorA
      to:   trackerA

    - from: trackerA
      to:   spatial_analyzer

    - from: spatial_analyzer
      to:   people_counter

    - from: people_counter
      to:   count_condition

    - from: count_condition
      to:   publisherA


subscribers:
  - type: mail
    listen: [count_exceeded_event]
    params:
      sender: mail1
      to: [ops@company.com]
      password: TRACKEY_SMTP_PASSWORD

renderer:
    type: opencv

sinks:
  - type: display
    params:
      window_name: Trackey
