source:
  type: camera
  params:
    index: 0
    width: 1280 # resize before pipeline — all nodes see 1280x720
    height: 720

scene:
  zones:
    - name: Entrance
      polygon:
        - [0.1,0.3] # zone top left
        - [1.0,0.3] # zone top right
        - [1.0,1.0] # zone buttom right
        - [0.1,1.0] # zone buttom left

pipeline:
  nodes:
    - name: detectorA
      type: detector
      processor: yolo
      source: primary
      params:
        weights: yolov8n.pt
    - name: trackerA
      type: tracker
      processor: deepsort
      params:
        max_age: 4
        n_init: 3
        nms_max_overlap: 0.5
        max_cosine_distance: 0.3
        nn_budget: 100
    - name: spatial_analyzer
      type: spatial_index
    - name: people_counter
      type: analyzer
      processor: counter
      zone_name: Entrance
      params:
        target_classes:
          - person
        metrics:
          - current
          - cumulative
    - name: face_detector
      type: detector
      processor: retinaface
      source: faces
    - name: reid
      type: reid
      processor: osnet
      zone_name: Entrance
    - name: count_condition
      type: condition
      params:
        path: analytics.people_counter.person.cumulative
        operator: gte
        threshold: 2
        true_output: publisherA
    - name: publisherA
      type: publisher
      events:
        - type: count_exceeded_event
          extract:
            count:        analytics.people_counter.person.cumulative
            zone_name:    analytics.people_counter.zone_name

  edges:
    - from: detectorA
      to:   trackerA

    - from: trackerA
      to:   spatial_analyzer

    - from: spatial_analyzer
      to:   people_counter

    - from: people_counter
      to:   count_condition

    - from: count_condition
      to:   publisherA
    
    - from: spatial_analyzer
      to:   reid


subscribers:
  - type: mail
    listen: [count_exceeded_event]
    params:
      sender: mail1
      to: [mail1, mail2, emd9810@gmail.com]
      password_env: TRACKEY_SMTP_PASSWORD
      throttle_seconds: 98
  - type: null_subscriber
    listen: [count_exceeded_event]
    throttle_seconds: 10

renderer:
  type: opencv
  styles:
    detections:
      show:       true
      show_bbox:  true
      show_label: true
      bbox:
        color:     [200, 200, 255]
        thickness: 1
      label:
        color:    [0, 0, 0]
        font_size: 0.6

    tracks:
      show:       true
      show_bbox:  true
      show_id:    true
      show_trail: false
      show_label: true
      bbox:
        color:     [255, 111, 0]
        thickness: 1
      id_label:
        color:     [0, 0, 0]
        font_size: 0.6
      label:
        color:    [0, 255, 0]
        font_size: 0.6
      trail:
        color:      [0, 0, 255]
        max_points: 20
        thickness:  4
        fade_mode:  alpha
        min_alpha:  0.1

    zones:
      show:         true
      Entrance:
        show:       true
        show_label: true
        polygon:
          color:     [255, 255, 0]
          filled:    true
          alpha:     0.2
          thickness: 2
        label:
          color:     [0, 0, 0]
          font_size: 0.6
    
    lines:
      show:           true
      StartLine:
        show:         true
        show_label:   true
        line:
          color:     [255, 255, 0]
        label:
          color:     [0, 255, 255]

    analytics:
      show: false
      people_counter:
        show:      false
        position:  [0.1, 0.3]
        show_keys: []
        panel:
          color:  [0, 0, 0]
          alpha:  0.6
          filled: true
        text:
          color:     [255, 255, 255]
          font_size: 0.5

sinks:
  - type: display
    params:
      window_name: Trackey
